---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      image: nginx
  template:
    metadata:
      labels:
        image: nginx
    spec:
      containers:
      - name: ctr-nginx
        image: nginx
...
