---
apiVersion: v1
kind: Service
metadata:
  name: svc25-np
spec:
  type: NodePort
  selector:
    tag: label25
  ports:
  - name: port25
    protocol: TCP
    port: 8080  # this is the service port
    targetPort: 80 # this is the container port
...
