---
apiVersion: v1
kind: Service
metadata:
  name: svc29-nfs
spec:
  selector:
    tag: label29-nfs
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
...

