---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: default
spec:
  containers:
  - name: ctr3
    image: polinux/stress
    resources:
      requests:
        memory: "900Gi"
      limits:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "120M", "--vm-hang", "1"]
...
