---
kind: Job
apiVersion: batch/v1
metadata:
  name: job33
spec:
  completions: 9  # default is 1
  parallelism: 3  # default is 1
  template:
    spec:
      containers:
      - name: ctr33
        image: ubuntu
        command:
        - "/bin/bash"
        - "-c"
        - "echo Hi!; echo This hostname is ; hostname; echo The date/time is; date"
      restartPolicy: Never  # default is 'Always' which isn't supported by Job
      # supported restart polices are 'Never', 'OnFailure'
...
