---
apiVersion: v1
kind: Pod
metadata:
  name: po4
  namespace: default
spec:
  containers:
  - name: ctr4
    image: vish/stress
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "1"
    args: ["-cpus", "2"]  #attempt to use 2 CPUs
...
